---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: apache2
      state: latest
  - name: write the apache config file
    template:
      src: /etc/apache2/apache2.conf
      dest: /etc/apache2/apache2.conf
    notify:
    - restart apache2
  - name: ensure apache is running
    service:
      name: apache2
      state: started
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
